### PR TITLE
My demo of OncoKB idea extension.

### PR DESCRIPTION
**Pull request by URestrepo**
This is my Jupyter Notebook not using a MAF file. The notebook uses a study from cBioPortal for annotations.

I utilized the cBioPortal's mutations and clinical endpoints for the study with the most samples count. I then used OncoKB's REST API to annotate the gene mutations. 

I created visualizations to compare levels of evidence and VUS (a variant of unknown significance). The visualizations showed that VUS gene mutations are a superset of genes with level 1 evidence (FDA-recognized biomarkers). 

A pie chart was also created to visualize the highest occurring CANCER_TYPE in the study indexed by levels of evidence.

### CODE REVIEW

**Comment by inodb** [comment]
Really cool @URestrepo ! Well done! Could you put the notebook in the `1-ideas/annotate-oncokb-barchart` folder? Thanks!

**Comment by URestrepo** [comment]
@inodb It has been done. Thank you for checking!

**Comment by inodb** [comment]
@URestrepo Perfect! Thank you!

**Comment by inodb** [comment]
@URestrepo if u want to add more changes, feel free to send another PR. Thanks for making this!

**Comment by inodb** [comment]
@URestrepo one minor improvement could be to use POST here:

```
oncokb.Annotations.annotateMutationsByProteinChangeGetUsingGET(entrezGeneId=m.entrezGeneId, alteration=m.proteinChange).result()))
```

That will send a single request instead and should be a lot faster

**Pull request merged**
